# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_likelihoodc', [dirname(__file__)])
        except ImportError:
            import _likelihoodc
            return _likelihoodc
        if fp is not None:
            try:
                _mod = imp.load_module('_likelihoodc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _likelihoodc = swig_import_helper()
    del swig_import_helper
else:
    import _likelihoodc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def calc_alpha(*args):
  return _likelihoodc.calc_alpha(*args)
calc_alpha = _likelihoodc.calc_alpha

def lnlognormal(*args):
  return _likelihoodc.lnlognormal(*args)
lnlognormal = _likelihoodc.lnlognormal

def ln_alpha_prior(*args):
  return _likelihoodc.ln_alpha_prior(*args)
ln_alpha_prior = _likelihoodc.ln_alpha_prior

def lnprior(*args):
  return _likelihoodc.lnprior(*args)
lnprior = _likelihoodc.lnprior

def lnlike(*args):
  return _likelihoodc.lnlike(*args)
lnlike = _likelihoodc.lnlike

def lnprob_func_gradient_descent(*args):
  return _likelihoodc.lnprob_func_gradient_descent(*args)
lnprob_func_gradient_descent = _likelihoodc.lnprob_func_gradient_descent
# This file is compatible with both classic and new-style classes.


