# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_likelihoodc')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_likelihoodc')
    _likelihoodc = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_likelihoodc', [dirname(__file__)])
        except ImportError:
            import _likelihoodc
            return _likelihoodc
        try:
            _mod = imp.load_module('_likelihoodc', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _likelihoodc = swig_import_helper()
    del swig_import_helper
else:
    import _likelihoodc
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def calc_alpha(dx, dv, nstars):
    return _likelihoodc.calc_alpha(dx, dv, nstars)
calc_alpha = _likelihoodc.calc_alpha

def lnlognormal(x, mu, sig):
    return _likelihoodc.lnlognormal(x, mu, sig)
lnlognormal = _likelihoodc.lnlognormal

def ln_alpha_prior(dx, dv, memb_probs, sig, nstars):
    return _likelihoodc.ln_alpha_prior(dx, dv, memb_probs, sig, nstars)
ln_alpha_prior = _likelihoodc.ln_alpha_prior

def lnprior(mean, mean_dim, covmatrix, dx, dv, age, memb_probs, nstars):
    return _likelihoodc.lnprior(mean, mean_dim, covmatrix, dx, dv, age, memb_probs, nstars)
lnprior = _likelihoodc.lnprior

def lnlike(gr_mn, gr_mn_dim, gr_cov, gr_dim1, gr_dim2, st_mns, st_mn_dim1, st_mn_dim2, st_covs, st_dim1, st_dim2, st_dim3, memb_probs, nstars):
    return _likelihoodc.lnlike(gr_mn, gr_mn_dim, gr_cov, gr_dim1, gr_dim2, st_mns, st_mn_dim1, st_mn_dim2, st_covs, st_dim1, st_dim2, st_dim3, memb_probs, nstars)
lnlike = _likelihoodc.lnlike

def lnprob_func_gradient_descent(pars, data):
    return _likelihoodc.lnprob_func_gradient_descent(pars, data)
lnprob_func_gradient_descent = _likelihoodc.lnprob_func_gradient_descent
# This file is compatible with both classic and new-style classes.


