# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_temporal_propagation', [dirname(__file__)])
        except ImportError:
            import _temporal_propagation
            return _temporal_propagation
        if fp is not None:
            try:
                _mod = imp.load_module('_temporal_propagation', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _temporal_propagation = swig_import_helper()
    del swig_import_helper
else:
    import _temporal_propagation
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def convert_cart2curvilin(*args):
  return _temporal_propagation.convert_cart2curvilin(*args)
convert_cart2curvilin = _temporal_propagation.convert_cart2curvilin

def convert_curvilin2cart(*args):
  return _temporal_propagation.convert_curvilin2cart(*args)
convert_curvilin2cart = _temporal_propagation.convert_curvilin2cart

def epicyclic_approx(*args):
  return _temporal_propagation.epicyclic_approx(*args)
epicyclic_approx = _temporal_propagation.epicyclic_approx

def trace_epicyclic_orbit(*args):
  return _temporal_propagation.trace_epicyclic_orbit(*args)
trace_epicyclic_orbit = _temporal_propagation.trace_epicyclic_orbit

def trace_epicyclic_covmatrix(*args):
  return _temporal_propagation.trace_epicyclic_covmatrix(*args)
trace_epicyclic_covmatrix = _temporal_propagation.trace_epicyclic_covmatrix
# This file is compatible with both classic and new-style classes.


