# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_temporal_propagation')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_temporal_propagation')
    _temporal_propagation = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_temporal_propagation', [dirname(__file__)])
        except ImportError:
            import _temporal_propagation
            return _temporal_propagation
        try:
            _mod = imp.load_module('_temporal_propagation', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _temporal_propagation = swig_import_helper()
    del swig_import_helper
else:
    import _temporal_propagation
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def convert_cart2curvilin(data, curvilin_coord):
    return _temporal_propagation.convert_cart2curvilin(data, curvilin_coord)
convert_cart2curvilin = _temporal_propagation.convert_cart2curvilin

def convert_curvilin2cart(data, cart_coord):
    return _temporal_propagation.convert_curvilin2cart(data, cart_coord)
convert_curvilin2cart = _temporal_propagation.convert_curvilin2cart

def epicyclic_approx(data, t, new_position):
    return _temporal_propagation.epicyclic_approx(data, t, new_position)
epicyclic_approx = _temporal_propagation.epicyclic_approx

def trace_epicyclic_orbit(xyzuvw_start, t, xyzuvw_new):
    return _temporal_propagation.trace_epicyclic_orbit(xyzuvw_start, t, xyzuvw_new)
trace_epicyclic_orbit = _temporal_propagation.trace_epicyclic_orbit

def trace_epicyclic_covmatrix(cov, loc, t, h, cov_transformed):
    return _temporal_propagation.trace_epicyclic_covmatrix(cov, loc, t, h, cov_transformed)
trace_epicyclic_covmatrix = _temporal_propagation.trace_epicyclic_covmatrix
# This file is compatible with both classic and new-style classes.


